package io.github.keddnyo.amazware

import android.content.Context
import android.net.Uri
import android.widget.EditText
import androidx.preference.PreferenceManager
import okhttp3.Request

class Extras {

    fun deviceRequest(ps: EditText, ds: EditText, av: EditText, an: EditText): Request {
        val requestHost = "api-mifit-ru.huami.com"

        val uriBuilder: Uri.Builder = Uri.Builder()
        uriBuilder.scheme("https")
            .authority(requestHost)
            .appendPath("devices")
            .appendPath("ALL")
            .appendPath("hasNewVersion")
            .appendQueryParameter("productId", "0")
            .appendQueryParameter("vendorSource", "0")
            .appendQueryParameter("resourceVersion", "0")
            .appendQueryParameter("firmwareFlag", "0")
            .appendQueryParameter("vendorId", "0")
            .appendQueryParameter("resourceFlag", "0")
            .appendQueryParameter("productionSource", "${ps.text}")
            .appendQueryParameter("userid", "0")
            .appendQueryParameter("userId", "0")
            .appendQueryParameter("deviceSource", "${ds.text}")
            .appendQueryParameter("fontVersion", "0")
            .appendQueryParameter("fontFlag", "3")
            .appendQueryParameter("appVersion", "${av.text}")
            .appendQueryParameter("appid", "0")
            .appendQueryParameter("callid", "0")
            .appendQueryParameter("channel", "0")
            .appendQueryParameter("country", "0")
            .appendQueryParameter("cv", "0")
            .appendQueryParameter("device", "0")
            .appendQueryParameter("deviceType", "ALL")
            .appendQueryParameter("device_type", "android_phone")
            .appendQueryParameter("firmwareVersion", "0")
            .appendQueryParameter("hardwareVersion", "0")
            .appendQueryParameter("lang", "0")
            .appendQueryParameter("support8Bytes", "true")
            .appendQueryParameter("timezone", "0")
            .appendQueryParameter("v", "0")
            .appendQueryParameter("gpsVersion", "0")
            .appendQueryParameter("baseResourceVersion", "0")

        return Request.Builder()
            .url(uriBuilder.toString())
            .addHeader("hm-privacy-diagnostics", "false")
            .addHeader("country", "0")
            .addHeader("appplatform", "android_phone")
            .addHeader("hm-privacy-ceip", "0")
            .addHeader("x-request-id", "0")
            .addHeader("timezone", "0")
            .addHeader("channel", "0")
            .addHeader("user-agent", "0")
            .addHeader("cv", "0")
            .addHeader("appname", "${an.text}")
            .addHeader("v", "0")
            .addHeader("apptoken", "0")
            .addHeader("lang", "0")
            .addHeader("Host", "api-mifit-ru.huami.com")
            .addHeader("Connection", "Keep-Alive")
            .addHeader("accept-encoding", "gzip")
            .addHeader("accept", "*/*")
            .build()
    }

    fun renameLang(context: Context, lang: String): String {
        val sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context) // Shared Preferences
        return when (sharedPreferences.getBoolean("lang_formatted", true)) {
            true -> {
                var l: String = lang.replace(",", " , ")
                l = l.replace(" ab",". ab .")
                l = l.replace("aa",". aa .")
                l = l.replace("af",". af .")
                l = l.replace("ak",". ak .")
                l = l.replace("sq",". sq .")
                l = l.replace("am",". am .")
                l = l.replace("ar",". ar .")
                l = l.replace("an",". an .")
                l = l.replace("hy",". hy .")
                l = l.replace("as",". as .")
                l = l.replace("av",". av .")
                l = l.replace("ae",". ae .")
                l = l.replace("ay",". ay .")
                l = l.replace("az",". az .")
                l = l.replace("ba",". ba .")
                l = l.replace("eu",". eu .")
                l = l.replace("be",". be .")
                l = l.replace("bn",". bn .")
                l = l.replace("bh",". bh .")
                l = l.replace("bi",". bi .")
                l = l.replace("bm",". bm .")
                l = l.replace("bs",". bs .")
                l = l.replace("br",". br .")
                l = l.replace("bg",". bg .")
                l = l.replace("my",". my .")
                l = l.replace("ca",". ca .")
                l = l.replace("ch",". ch .")
                l = l.replace("ce",". ce .")
                l = l.replace("ny",". ny .")
                l = l.replace("zh",". zh .")
                l = l.replace("cv",". cv .")
                l = l.replace("kw",". kw .")
                l = l.replace("co",". co .")
                l = l.replace("cr",". cr .")
                l = l.replace("hr",". hr .")
                l = l.replace("cs",". cs .")
                l = l.replace("da",". da .")
                l = l.replace("dv",". dv .")
                l = l.replace("nl",". nl .")
                l = l.replace("en",". en .")
                l = l.replace("eo",". eo .")
                l = l.replace("et",". et .")
                l = l.replace("ee",". ee .")
                l = l.replace("fo",". fo .")
                l = l.replace("fj",". fj .")
                l = l.replace("fi",". fi .")
                l = l.replace("fr",". fr .")
                l = l.replace("ff",". ff .")
                l = l.replace("gl",". gl .")
                l = l.replace("ka",". ka .")
                l = l.replace("de",". de .")
                l = l.replace("el",". el .")
                l = l.replace("gn",". gn .")
                l = l.replace("gu",". gu .")
                l = l.replace("ht",". ht .")
                l = l.replace("ha",". ha .")
                l = l.replace("he",". he .")
                l = l.replace("hz",". hz .")
                l = l.replace("hi",". hi .")
                l = l.replace("ho",". ho .")
                l = l.replace("hu",". hu .")
                l = l.replace("ia",". ia .")
                l = l.replace("id",". id .")
                l = l.replace("ie",". ie .")
                l = l.replace("ga",". ga .")
                l = l.replace("ig",". ig .")
                l = l.replace("ik",". ik .")
                l = l.replace("io",". io .")
                l = l.replace("is",". is .")
                l = l.replace("it",". it .")
                l = l.replace("iu",". iu .")
                l = l.replace("ja",". ja .")
                l = l.replace("jv",". jv .")
                l = l.replace("kl",". kl .")
                l = l.replace("kn",". kn .")
                l = l.replace("kr",". kr .")
                l = l.replace("ks",". ks .")
                l = l.replace("kk",". kk .")
                l = l.replace("km",". km .")
                l = l.replace("ki",". ki .")
                l = l.replace("rw",". rw .")
                l = l.replace("ky",". ky .")
                l = l.replace("kv",". kv .")
                l = l.replace("kg",". kg .")
                l = l.replace("ko",". ko .")
                l = l.replace("ku",". ku .")
                l = l.replace("kj",". kj .")
                l = l.replace("la",". la .")
                l = l.replace("lb",". lb .")
                l = l.replace("lg",". lg .")
                l = l.replace("li",". li .")
                l = l.replace("ln",". ln .")
                l = l.replace("lo",". lo .")
                l = l.replace("lt",". lt .")
                l = l.replace("lu",". lu .")
                l = l.replace("lv",". lv .")
                l = l.replace("gv",". gv .")
                l = l.replace("mk",". mk .")
                l = l.replace("mg",". mg .")
                l = l.replace("ms",". ms .")
                l = l.replace("ml",". ml .")
                l = l.replace("mt",". mt .")
                l = l.replace("mi",". mi .")
                l = l.replace("mr",". mr .")
                l = l.replace("mh",". mh .")
                l = l.replace("mn",". mn .")
                l = l.replace("na",". na .")
                l = l.replace("nv",". nv .")
                l = l.replace("nb",". nb .")
                l = l.replace("nd",". nd .")
                l = l.replace("ne",". ne .")
                l = l.replace("ng",". ng .")
                l = l.replace("nn",". nn .")
                l = l.replace("no",". no .")
                l = l.replace("ii",". ii .")
                l = l.replace("nr",". nr .")
                l = l.replace("oc",". oc .")
                l = l.replace("oj",". oj .")
                l = l.replace("cu",". cu .")
                l = l.replace("om",". om .")
                l = l.replace("or",". or .")
                l = l.replace("os",". os .")
                l = l.replace("pa",". pa .")
                l = l.replace("pi",". pi .")
                l = l.replace("fa",". fa .")
                l = l.replace("pl",". pl .")
                l = l.replace("ps",". ps .")
                l = l.replace("pt",". pt .")
                l = l.replace("qu",". qu .")
                l = l.replace("rm",". rm .")
                l = l.replace("rn",". rn .")
                l = l.replace("ro",". ro .")
                l = l.replace("ru",". ru .")
                l = l.replace("sa",". sa .")
                l = l.replace("sc",". sc .")
                l = l.replace("sc",". sc .")
                l = l.replace("se",". se .")
                l = l.replace("sm",". sm .")
                l = l.replace("sg",". sg .")
                l = l.replace("sr",". sr .")
                l = l.replace("gd",". gd .")
                l = l.replace("sn",". sn .")
                l = l.replace("si",". si .")
                l = l.replace("sk",". sk .")
                l = l.replace("sl",". sl .")
                l = l.replace("so",". so .")
                l = l.replace("st",". st .")
                l = l.replace("es",". es .")
                l = l.replace("su",". su .")
                l = l.replace("sw",". sw .")
                l = l.replace("ss",". ss .")
                l = l.replace("sv",". sv .")
                l = l.replace("ta",". ta .")
                l = l.replace("te",". te .")
                l = l.replace("tg",". tg .")
                l = l.replace("th",". th .")
                l = l.replace("ti",". ti .")
                l = l.replace("bo",". bo .")
                l = l.replace("tk",". tk .")
                l = l.replace("tl",". tl .")
                l = l.replace("tn",". tn .")
                l = l.replace("to",". to .")
                l = l.replace("tr",". tr .")
                l = l.replace("ts",". ts .")
                l = l.replace("tt",". tt .")
                l = l.replace("tw",". tw .")
                l = l.replace("ty",". ty .")
                l = l.replace("ug",". ug .")
                l = l.replace("uk",". uk .")
                l = l.replace("ur",". ur .")
                l = l.replace("uz",". uz .")
                l = l.replace("ve",". ve .")
                l = l.replace("vi",". vi .")
                l = l.replace("vo",". vo .")
                l = l.replace("wa",". wa .")
                l = l.replace("cy",". cy .")
                l = l.replace("wo",". wo .")
                l = l.replace("fy",". fy .")
                l = l.replace("xh",". xh .")
                l = l.replace("yi",". yi .")
                l = l.replace("yo",". yo .")
                l = l.replace("za",". za .")
                l = l.replace("in",". in .")
                l = l.replace("iw",". iw .")


                l = l.replace(". ab .",". Abkhaz .")
                l = l.replace(". aa .",". Afar .")
                l = l.replace(". af .",". Afrikaans .")
                l = l.replace(". ak .",". Akan .")
                l = l.replace(". sq .",". Albanian .")
                l = l.replace(". am .",". Amharic .")
                l = l.replace(". ar .",". Arabic .")
                l = l.replace(". an .",". Aragonese .")
                l = l.replace(". hy .",". Armenian .")
                l = l.replace(". as .",". Assamese .")
                l = l.replace(". av .",". Avaric .")
                l = l.replace(". ae .",". Avestan .")
                l = l.replace(". ay .",". Aymara .")
                l = l.replace(". az .",". Azerbaijani .")
                l = l.replace(". ba .",". Bashkir .")
                l = l.replace(". eu .",". Basque .")
                l = l.replace(". be .",". Belarusian .")
                l = l.replace(". bn .",". Bengali .")
                l = l.replace(". bh .",". Bihari .")
                l = l.replace(". bi .",". Bislama .")
                l = l.replace(". bm .",". Bambara .")
                l = l.replace(". bs .",". Bosnian .")
                l = l.replace(". br .",". Breton .")
                l = l.replace(". bg .",". Bulgarian .")
                l = l.replace(". my .",". Burmese .")
                l = l.replace(". ca .",". Catalan .")
                l = l.replace(". ch .",". Chamorro .")
                l = l.replace(". ce .",". Chechen .")
                l = l.replace(". ny .",". Chewa .")
                l = l.replace(". zh .",". Chinese .")
                l = l.replace(". cv .",". Chuvash .")
                l = l.replace(". kw .",". Cornish .")
                l = l.replace(". co .",". Corsican .")
                l = l.replace(". cr .",". Cree .")
                l = l.replace(". hr .",". Croatian .")
                l = l.replace(". cs .",". Czech .")
                l = l.replace(". da .",". Danish .")
                l = l.replace(". dv .",". Maldivian .")
                l = l.replace(". nl .",". Dutch .")
                l = l.replace(". en .",". English .")
                l = l.replace(". eo .",". Esperanto .")
                l = l.replace(". et .",". Estonian .")
                l = l.replace(". ee .",". Ewe .")
                l = l.replace(". fo .",". Faroese .")
                l = l.replace(". fj .",". Fijian .")
                l = l.replace(". fi .",". Finnish .")
                l = l.replace(". fr .",". French .")
                l = l.replace(". ff .",". Pular .")
                l = l.replace(". gl .",". Galician .")
                l = l.replace(". ka .",". Georgian .")
                l = l.replace(". de .",". German .")
                l = l.replace(". el .",". Greek .")
                l = l.replace(". gn .",". Guaraní .")
                l = l.replace(". gu .",". Gujarati .")
                l = l.replace(". ht .",". Haitian .")
                l = l.replace(". ha .",". Hausa .")
                l = l.replace(". he .",". Hebrew .")
                l = l.replace(". hz .",". Herero .")
                l = l.replace(". hi .",". Hindi .")
                l = l.replace(". ho .",". Hiri Motu .")
                l = l.replace(". hu .",". Hungarian .")
                l = l.replace(". ia .",". Interlingua .")
                l = l.replace(". id .",". Indonesian .")
                l = l.replace(". ie .",". Interlingue .")
                l = l.replace(". ga .",". Irish .")
                l = l.replace(". ig .",". Igbo .")
                l = l.replace(". ik .",". Inupiaq .")
                l = l.replace(". io .",". Ido .")
                l = l.replace(". is .",". Icelandic .")
                l = l.replace(". it .",". Italian .")
                l = l.replace(". iu .",". Inuktitut .")
                l = l.replace(". ja .",". Japanese .")
                l = l.replace(". jv .",". Javanese .")
                l = l.replace(". kl .",". Greenlandic .")
                l = l.replace(". kn .",". Kannada .")
                l = l.replace(". kr .",". Kanuri .")
                l = l.replace(". ks .",". Kashmiri .")
                l = l.replace(". kk .",". Kazakh .")
                l = l.replace(". km .",". Khmer .")
                l = l.replace(". ki .",". Kikuyu .")
                l = l.replace(". rw .",". Kinyarwanda .")
                l = l.replace(". ky .",". Kirghiz .")
                l = l.replace(". kv .",". Komi .")
                l = l.replace(". kg .",". Kongo .")
                l = l.replace(". ko .",". Korean .")
                l = l.replace(". ku .",". Kurdish .")
                l = l.replace(". kj .",". Kwanyama .")
                l = l.replace(". la .",". Latin .")
                l = l.replace(". lb .",". Luxembourgish .")
                l = l.replace(". lg .",". Luganda .")
                l = l.replace(". li .",". Limburgish .")
                l = l.replace(". ln .",". Lingala .")
                l = l.replace(". lo .",". Lao .")
                l = l.replace(". lt .",". Lithuanian .")
                l = l.replace(". lu .",". Luba-Katanga .")
                l = l.replace(". lv .",". Latvian .")
                l = l.replace(". gv .",". Manx .")
                l = l.replace(". mk .",". Macedonian .")
                l = l.replace(". mg .",". Malagasy .")
                l = l.replace(". ms .",". Malay .")
                l = l.replace(". ml .",". Malayalam .")
                l = l.replace(". mt .",". Maltese .")
                l = l.replace(". mi .",". Māori .")
                l = l.replace(". mr .",". Marathi .")
                l = l.replace(". mh .",". Marshallese .")
                l = l.replace(". mn .",". Mongolian .")
                l = l.replace(". na .",". Nauru .")
                l = l.replace(". nv .",". Navajo .")
                l = l.replace(". nb .",". Norwegian Bokmål .")
                l = l.replace(". nd .",". North Ndebele .")
                l = l.replace(". ne .",". Nepali .")
                l = l.replace(". ng .",". Ndonga .")
                l = l.replace(". nn .",". Norwegian Nynorsk .")
                l = l.replace(". no .",". Norwegian .")
                l = l.replace(". ii .",". Nuosu .")
                l = l.replace(". nr .",". South Ndebele .")
                l = l.replace(". oc .",". Occitan .")
                l = l.replace(". oj .",". Ojibwe .")
                l = l.replace(". cu .",". Slavonic .")
                l = l.replace(". om .",". Oromo .")
                l = l.replace(". or .",". Oriya .")
                l = l.replace(". os .",". Ossetian .")
                l = l.replace(". pa .",". Panjabi .")
                l = l.replace(". pi .",". Pāli .")
                l = l.replace(". fa .",". Persian .")
                l = l.replace(". pl .",". Polish .")
                l = l.replace(". ps .",". Pashto .")
                l = l.replace(". pt .",". Portuguese .")
                l = l.replace(". qu .",". Quechua .")
                l = l.replace(". rm .",". Romansh .")
                l = l.replace(". rn .",". Kirundi .")
                l = l.replace(". ro .",". Romanian .")
                l = l.replace(". ru .",". Russian .")
                l = l.replace(". sa .",". Sanskrit .")
                l = l.replace(". sc .",". Sardinian .")
                l = l.replace(". sd .",". Sindhi .")
                l = l.replace(". se .",". Northern Sami .")
                l = l.replace(". sm .",". Samoan .")
                l = l.replace(". sg .",". Sango .")
                l = l.replace(". sr .",". Serbian .")
                l = l.replace(". gd .",". Gaelic .")
                l = l.replace(". sn .",". Shona .")
                l = l.replace(". si .",". Sinhala .")
                l = l.replace(". sk .",". Slovak .")
                l = l.replace(". sl .",". Slovene .")
                l = l.replace(". so .",". Somali .")
                l = l.replace(". st .",". Southern Sotho .")
                l = l.replace(". es .",". Spanish .")
                l = l.replace(". su .",". Sundanese .")
                l = l.replace(". sw .",". Swahili .")
                l = l.replace(". ss .",". Swati .")
                l = l.replace(". sv .",". Swedish .")
                l = l.replace(". ta .",". Tamil .")
                l = l.replace(". te .",". Telugu .")
                l = l.replace(". tg .",". Tajik .")
                l = l.replace(". th .",". Thai .")
                l = l.replace(". ti .",". Tigrinya .")
                l = l.replace(". bo .",". Tibetan .")
                l = l.replace(". tk .",". Turkmen .")
                l = l.replace(". tl .",". Tagalog .")
                l = l.replace(". tn .",". Tswana .")
                l = l.replace(". to .",". Tonga .")
                l = l.replace(". tr .",". Turkish .")
                l = l.replace(". ts .",". Tsonga .")
                l = l.replace(". tt .",". Tatar .")
                l = l.replace(". tw .",". Twi .")
                l = l.replace(". ty .",". Tahitian .")
                l = l.replace(". ug .",". Uighur .")
                l = l.replace(". uk .",". Ukrainian .")
                l = l.replace(". ur .",". Urdu .")
                l = l.replace(". uz .",". Uzbek .")
                l = l.replace(". ve .",". Venda .")
                l = l.replace(". vi .",". Vietnamese .")
                l = l.replace(". vo .",". Volapük .")
                l = l.replace(". wa .",". Walloon .")
                l = l.replace(". cy .",". Welsh .")
                l = l.replace(". wo .",". Wolof .")
                l = l.replace(". fy .",". Western Frisian .")
                l = l.replace(". xh .",". Xhosa .")
                l = l.replace(". yi .",". Yiddish .")
                l = l.replace(". yo .",". Yoruba .")
                l = l.replace(". za .",". Zhuang .")
                l = l.replace(". in .",". former Indonesian .")
                l = l.replace(". iw .",". former Hebrew .")
                l = l.replace(". ","")
                l = l.replace(" .","")
                l.replace(" , ",", ")
            }
            false -> {
                lang.replace(",", ", ")
            }
        }
    }
}